# Generated by Django 6.0.5 on 2026-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='entry_fee',
            field=models.CharField(blank=True, default='Free', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='timings',
            field=models.CharField(blank=True, default='Open all day', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='visit_duration',
            field=models.CharField(blank=True, default='1-2 hours', max_length=100),
        ),
    ]
